# Generated by Django 2.1.5 on 2020-06-11 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20200612_0116'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ReadNun',
            new_name='ReadNum',
        ),
    ]
